services:
  backend:
    build: .
    container_name: ${APP_NAME:-backend_api}
    env_file: .env
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      clamav:
        condition: service_healthy
      mailhog:
        condition: service_started
    restart: unless-stopped
    environment:
      DATABASE_URL: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}?replicaSet=rs0&authSource=admin"
    ports:
      - "${PORT:-3000}:3000"
    networks:
      - backend_network
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=${PORT:-3000}"
      - "prometheus.path=/metrics"

  mongo:
    image: mongo:6.0-jammy
    container_name: ${MONGO_NAME:-mongo_db}
    restart: unless-stopped
    entrypoint: ["/scripts/start-mongo.sh"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-securepassword}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-admin}
    volumes:
      - ./mongo-keyfile:/mongo-keyfile:ro
      - ./scripts/start-mongo.sh:/scripts/start-mongo.sh:ro
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT:-27017}:27017"
    networks:
      - backend_network
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "-u",
          "${MONGO_USER:-admin}",
          "-p",
          "${MONGO_PASSWORD:-securepassword}",
          "--authenticationDatabase",
          "admin",
          "--eval",
          "rs.status().ok || rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}).ok",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 90s
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=9216"

  mongo-backup:
    image: mongo:6.0
    volumes:
      - ./backups:/backups
    environment:
      - MONGO_URI=${MONGO_URL:-mongodb://admin:securepassword@mongo:27017/admin?replicaSet=rs0&authSource=admin}
    entrypoint: |
      bash -c 'while true; do
        echo "Running backup at $(date)"
        mongodump --uri="$$MONGO_URI" --gzip --archive=/backups/dump_$$(date +%Y%m%d_%H%M%S).gz
        sleep 86400  # Attendre 24h
      done'
    depends_on:
      - mongo

  redis:
    image: redis:8-alpine
    container_name: ${REDIS_NAME:-redis_cache}
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=9121"

  redisinsight:
    image: redis/redisinsight:2.54.0
    container_name: ${REDISINSIGHT_NAME:-redisinsight}
    ports:
      - "${REDISINSIGHT_PORT:-8001}:5540"
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - backend_network
    volumes:
      - redisinsight_data:/data
    environment:
      - REDIS_HOSTS=local:redis:6379
      - RIHOST=0.0.0.0
      - RIPORT=8001

  minio:
    image: minio/minio:RELEASE.2023-10-25T06-33-25Z
    container_name: ${MINIO_NAME:-minio_storage}
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001" --address ":9000"
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE:-9001}:9001"
    volumes:
      - minio_data:/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio-init:
    image: minio/mc:latest
    container_name: MINIO_INITIALIZER
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/scripts/init-minio.sh"]
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_APP_BUCKET: ${MINIO_APP_BUCKET}
    volumes:
      - ./scripts/init-minio.sh:/scripts/init-minio.sh:ro
    networks:
      - backend_network

  mailhog:
    image: mailhog/mailhog
    container_name: ${SMTP_NAME:-mail}
    restart: unless-stopped
    ports:
      - "${SMTP_PORT:-1025}:1025" # SMTP
      - "${SMTP_WEB_UI:-8025}:8025" # Web UI
    networks:
      - backend_network

  nginx:
    image: nginx:stable-alpine
    container_name: ${NGINX_NAME:-nginx}
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSH:-443}:443"
    networks:
      - backend_network

  clamav:
    image: clamav/clamav:1.0.9
    container_name: ${CLAMAV_NAME:-clamav}
    environment:
      - CLAMAV_NO_CLAMD=false
      - CLAMAV_NO_FRESHCLAMD=false
      - CLAMD_STARTUP_TIMEOUT=600
      - CLAMD_STARTUP_SLEEP=60
      - CLAMD_CONNECT_TIMEOUT=60
      - CLAMD_STREAM_MAX_LENGTH=100M
      - FRESHCLAM_CHECKS=4
      - CLAMD_HOST=0.0.0.0
      - CLAMD_EXTRA_ARGS=--foreground --stream-max-ratio=300 --max-queue=100 --max-threads=8
      - FRESHCLAM_MOD=3600
      - FRESHCLAM_ONLYREQUIRED=1
    volumes:
      - clamav_data:/var/lib/clamav
      - ./monitoring/clamav/clamd.conf:/etc/clamav/clamd.conf
      - clamav_logs:/var/log/clamav
    ports:
      - "${CLAMAV_PORT:-3310}:3310"
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "clamdscan", "--version"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 120s
    command: ["sh", "-c", "freshclam --daemon --stdout && clamd --foreground"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 512M

volumes:
  mongo_data:
  minio_data:
  clamav_data:
  clamav_logs:
  redisinsight_data:

networks:
  backend_network:
    driver: bridge
    attachable: true
